# Cloudflare Pages Configuration
name = "transpal-astro"
compatibility_date = "2024-01-01"

[build]
command = "npm run build:production"
publish = "dist"

[build.environment_variables]
NODE_VERSION = "20"
NPM_VERSION = "10"

# Environment-specific configurations
[env.production]
name = "transpal-astro"

[env.preview]
name = "transpal-astro-preview"

# Custom domains (to be configured in Cloudflare dashboard)
# routes = [
#   { pattern = "transpal.example.com", custom_domain = true }
# ]

# Page Rules for additional optimization
[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
X-XSS-Protection = "1; mode=block"
Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
for = "/_astro/*"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/speeches/*"
[headers.values]
Cache-Control = "public, max-age=86400, must-revalidate"